name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: kotlin-yellowduck-sports

      - name: Checkout gpx repo
        uses: actions/checkout@v2
        with:
          repository: pieterclaerhout/kotlin-yellowduck-gpx
          path: kotlin-yellowduck-gpx


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: cd kotlin-yellowduck-sports && chmod +x gradlew

      - name: Build with Gradle
        run: cd kotlin-yellowduck-sports && ./gradlew build --scan
